<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Join Twitter today_gsi_131986_291961</name>
   <tag></tag>
   <elementGuidId>dd6ed64a-4fc4-489b-bf1b-a25f37f5930b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_131986_291961']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_131986_291961</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6ecdb506-de27-45b1-b2b7-27df9938742d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;shape=circle&amp;logo_alignment=center&amp;text=signup_with&amp;width=300&amp;client_id=49625052041-kgt0hghf445lmcmhijv46b715m2mpbct.apps.googleusercontent.com&amp;iframe_id=gsi_131986_291961&amp;as=u%2FWp%2Fv%2Fez9MREqgYBVAi8A&amp;hl=en</value>
      <webElementGuid>4b1f143c-77cf-4900-b97b-7a47e1fc254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_131986_291961</value>
      <webElementGuid>d567bef8-c700-490f-b549-9fdfbe85f897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tombol Login dengan Google</value>
      <webElementGuid>d8d3ec0c-696d-4d22-8808-f5c8bb2fa20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_131986_291961&quot;)</value>
      <webElementGuid>4267f359-a6f7-49af-bef0-d68f476307c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_131986_291961']</value>
      <webElementGuid>b55093e2-542b-4979-b28d-6dfeeb80150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/div/div/div[2]/main/div/div/div/div/div/div[3]/div/div/iframe</value>
      <webElementGuid>92e58dfe-7256-416a-aed5-d419d22feb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>71a6427b-ab2d-407c-887c-fa0813bc9d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?theme=outline&amp;size=large&amp;shape=circle&amp;logo_alignment=center&amp;text=signup_with&amp;width=300&amp;client_id=49625052041-kgt0hghf445lmcmhijv46b715m2mpbct.apps.googleusercontent.com&amp;iframe_id=gsi_131986_291961&amp;as=u%2FWp%2Fv%2Fez9MREqgYBVAi8A&amp;hl=en' and @id = 'gsi_131986_291961' and @title = 'Tombol Login dengan Google']</value>
      <webElementGuid>1a5c6ab9-9020-4495-b3b6-3cc7ff6ff630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
